sonar.projectKey=Alshammarii555_8.2CDevSecOps
sonar.organization=alshammarii555
sonar.host.url=https://sonarcloud.io
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
